name: "Task Template"
description: Template for weekly development tasks with clear criteria and definitions.
title: "⚠️ Task: [Phase] - [Feature Name]"
labels: []
assignees: []

body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: input
    id: estimated-time
    attributes:
      label: Estimated Time
    validations:
      required: false

  - type: input
    id: week
    attributes:
      label: Week
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Setup
        - Auth
        - Database
        - Frontend
        - Backend
        - Testing
        - Deployment
        - Documentation
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: checkboxes
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      options:
        - label: Specific, measurable criteria
        - label: That define when the task is complete
        - label: Include testing requirements

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Notes
    validations:
      required: false

  - type: checkboxes
    id: definition-of-done
    attributes:
      label: Definition of Done
      options:
        - label: Code written and working locally
        - label: Self-reviewed for quality and best practices
        - label: Tests written (if applicable)
        - label: Documentation updated
        - label: Feature deployed and tested
        - label: Ready for optional peer review
